src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Trick::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $trick;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="reply")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="parent")
     */
    private $reply;

    public function __construct()
    {
        $this->reply = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTrick(): ?Trick
    {
        return $this->trick;
    }

    public function setTrick(?Trick $trick): self
    {
        $this->trick = $trick;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getReply(): Collection
    {
        return $this->reply;
    }

    public function addReply(self $reply): self
    {
        if (!$this->reply->contains($reply)) {
            $this->reply[] = $reply;
            $reply->setParent($this);
        }

        return $this;
    }

    public function removeReply(self $reply): self
    {
        if ($this->reply->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getParent() === $this) {
                $reply->setParent(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Media;
use App\Entity\Trick;
use App\Form\UserType;
use App\Entity\Category;
use App\Form\EditTrickType;
use App\Services\DocUploader;
use App\Services\MediaUploader;
use App\Repository\TrickRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;

class MainController extends AbstractController
{


    public function __construct(TrickRepository $repoTricks)
    {
        $this->repository = $repoTricks;

        // if($this->getUser() && !$this->getUser()->getIsVerified()){
        //     $this->addFlash('message','You need to verify your adress. Check your mails.');
        //     return $this->redirectToRoute('app_logout');
        // }
    }

    /**
     * @Route("/", name="app_home")
     */
    public function index(Request $request): Response
    {
        $user = $this->getUser();
        if ($user && $user->IsVerified() === false) {
            $this->addFlash('success', 'Check your emails to verify your email and enjoy all the fun. ');
        }
        $incrementTricks = 15;
        $start = $request->query->get('showTricks');
        if ($start === NULL) $start = 0;
        else $start = intval($start);
        $tricks = $this->repository->showTricks($start + $incrementTricks);
        $allTricksQty = count($this->repository->findAll());
        return $this->render('main/homePage.html.twig', [
            'controller_name' => 'MainController',
            'current_menu' => 'home',
            'tricks' => $tricks,
            'allTricksQty' => $allTricksQty
        ]);
    }

    /**
     * @route("/tricks", name="app_tricks") 
     */
    public function allTrick()
    {
        $tricks = $this->repository->findAll();
        return $this->render('main/allTricks.html.twig', [
            'tricks' => $tricks
        ]);
    }

    /**
     * @route("/profil/addTrick", name="app_add_trick") 
     */
    public function addTrick(Request $request, SluggerInterface $slugger)
    {
        $trick = new Trick;

        // $category =$this->getDoctrine()->getRepository(Category::class)->findAll();

        $form = $this->createForm(EditTrickType::class, $trick);
        $form->handleRequest($request);
        if ($form->isSubmitted()  && $form->isValid()) {

            $files = $form->get('media')->getData();

            if ($files) {
                foreach ($files as $file) {
                    // $type = $this->defineType();
                    // $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                    // $safeFilename = $slugger->slug($originalFilename);
                    // $newFilename = $safeFilename . '-' . uniqid() . '.' . $media->guessExtension();
                    // $newMedia = new FileUploader($image, $slugger);

                    $newFile = new MediaUploader('uploads', $slugger, $file);
                    dd($newFile);
                    $newFile->add($file);
                    dd($newFile);
                    $media = new Media;

                    // $video->setFilename();

                }
            }

            $trick->setCreatedAt(new \dateTime());
            $em = $this->getDoctrine()->getManager();
            $em->persist($trick);
            $em->flush();
            $this->addFlash('success', 'You added a new trick !');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('main/addTrick.html.twig', [
            'form' => $form->createView(),

        ]);
    }
    /**
     * @Route("/profil/deleteTrick/{id}", name="app_trick_delete")
     */
    public function delete(Request $request, int $id): Response
    {
        $trick = $this->repository->findOneBy(['id' => $id]);

        if ($this->isCsrfTokenValid('delete' . $trick->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trick);
            $entityManager->flush();

            $this->addFlash('success', 'The trick has been deleted !');
            return $this->redirectToRoute('app_home');
        }
    }
    /**
     * @route("/profil/edit/{id}", name="app_trick_edit") 
     */
    public function editTrick(int $id, Request $request)
    {
        $trick = $this->repository->findOneBy(['id' => $id]);
        $idCategory = $trick->getCategory();
        $category = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $form = $this->createForm(EditTrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $trick->setUpdateAt(new \dateTime());
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            $this->addFlash('success', 'This trick has been updated ');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('main/ediTrick.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
            'category' => $category
        ]);
    }

    /**
     * @route("/trick/{slug}", name="app_trick") 
     */
    public function showTrick(String $slug)
    {
        $trick = $this->repository->findOneBy(['slug' => $slug]);
        $slug = $trick->getSlug();

        return $this->render('main/trick.html.twig', [
            'trick' => $trick
        ]);
    }

    /**
     * @route("profil/editProfil/{id}",name="app_editProfil")
     */
    public function editProfil(Request $request, int $id, SluggerInterface $slugger)
    {

        $id = $id;
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->findOneBy(['id' => $id]);
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $avatarfile = $form->get('avatar')->getData();
            if($avatarfile){
                $originalFilename = pathinfo($avatarfile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$avatarfile->guessExtension();
               
                try {
                    $avatarfile->move(
                        $this->getParameter('media_directory'),
                        $newFilename
                    );
                    $em = $this->getDoctrine()->getManager();
                    $user->setAvatar($newFilename);
                    $em->flush();
                } catch (FileException $e) {
                    $this->addFlash('error', 'Something went wrong');
                }

            }
            $em = $this->getDoctrine()->getManager();
            $user->setAvatar($newFilename);
            $em->flush();
            $this->addFlash('success', 'You did great !');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('main/editProfil.html.twig', ['user' => $user, 'form'=>$form->createView()]);
    }
}

templates/main/addTrick.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a new Trick !!{% endblock %}

{% block body %}

    <h1 class="center mab-2 mat-2">Add a new amazing trick !</h1>
<div class="center">{{ form_start(form) }}
    <div class="center d-flex column mab-2 mat-1">
    {{ form_label(form.name) }}
    {{ form_widget(form.name) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.slug) }}
        {{ form_widget(form.slug) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.category) }}
        {{ form_widget(form.category) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.videoLink) }}
        {{ form_widget(form.videoLink) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.OnTopPic) }}
        {{ form_widget(form.OnTopPic) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.media) }}
        {{ form_widget(form.media) }}
    </div>
    {{ form_end(form) }}
</div>
       
{% endblock %}

templates/main/changeTopPicture.html.twig
{% extends 'base.html.twig' %}

{% block title %}Change Top picture {{ trick.name }}!{% endblock %}

{% block body %}
<h1 class="center">Change top picture</h1>
<h2 class="center">Pick the picture you wanna see on top !</h2>
<div class="mediaContainer mat-2">
    {{ form_start(form)}}
    {% for media in medias %}
    {% if media.type == "image" %}
        <img src="{{ asset('/uploads/' ~ media.filename)}}" alt="Image 1" class="thumbnail" />
        {{ form_widget(form.onTop)}}
        
        {% endif %}
    {% endfor %}
    {{ form_end(form)}}
</div>



{% endblock %}

templates/main/ediTrick.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit {{ trick.name }} trick!{% endblock %}

{% block body %}


<h1 class="center mab-2 mat-2">Edit {{ trick.name }}</h1>
<div>
    <hero style="background-image:url({{ asset('/uploads/' ~ trick.onTopPic) }})">
        {% if app.user and app.user.isVerified %}
        <h1 class="center">{{ trick.name }}</h1>
        <i class="fas fa-pencil-alt mar-2" onclick="showHideImageUploader()"></i>

        <form method="post" action="{{ path('app_OnTopPic_delete', {'id': trick.id}) }}"
            onsubmit="return confirm('Are you sure you want to delete this amazing picture?');">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
            <button class="fas"><i class="fas fa-trash-alt mr-2"></i></button>
        </form>
        {% endif %}
    </hero>
</div>
<div class="center">{{ form_start(form) }}
    <div class="center d-flex column mab-2 mat-1 hidden">
        {{ form_label(form.OnTopPic) }}
        {{ form_widget(form.OnTopPic) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.name) }}
        {{ form_widget(form.name) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.slug) }}
        {{ form_widget(form.slug) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.category) }}
        {{ form_widget(form.category) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.videoLink) }}
        {{ form_widget(form.videoLink) }}
    </div>
    <div class="center d-flex column mab-2 mat-1">
        {{ form_label(form.media) }}
        {{ form_widget(form.media) }}
    </div>
    <div>
        {{ form_widget(form.Save) }}
        {{ form_end(form) }}

        <form method="post" action="{{ path('app_trick_delete', {'id': trick.id}) }}"
            onsubmit="return confirm('Are you sure you want to delete this amazing trick?');">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
            <button class="btn-danger">Delete</button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascripts %}
<script>
    function showHideImageUploader() {
        document.getElementsByClassName("center d-flex column mab-2 mat-1")[0].classList.toggle("hidden");
    }
</script>
{% endblock %}

templates/main/editProfil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit my profil !{% endblock %}


{% block body %}

<h1 class="center mab-2"> My profil</h1>
<div class="d-flex center">
<div class="card  mab-2" style="width: 18rem;">
    <img src="{{ asset('/uploads/' ~ user.avatar)}}" alt="avatar" id="avatar" class="avatar">
    <div class="card-body d-flex center">
        <p class="">{{ user.username }}</p>
    </div>
</div>
</div>
<h2 class="center">Add a username and my awesome picture</h2>
<div class="center">
    {{ form_start(form) }}
    <div class="center d-flex column mab-2 mat-1">
    {{form_label(form.username) }}
    {{form_widget(form.username) }}
</div>
<div class="center d-flex column mab-2 mat-1">
    {{ form_label(form.avatar) }}
    {{ form_widget(form.avatar) }}
</div>
    {{ form_end(form) }}
</div>

{% endblock %}

templates/main/homePage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome on SnowTrick website!{% endblock %}
{% block javascripts %}

{% endblock %}
{% block body %}
<div class="jumbotron" style="background-image: url('https://media.gettyimages.com/photos/snowboarder-jumping-through-air-with-deep-blue-sky-in-background-picture-id1092719712?s=2048x2048');">
    <h1 id="up" class="center">Snowboard tricks and more</h1>
    <a href="#bloctricks"><i class="fas fa-arrow-down" id="arrow"></i></a>
</div>
{% for message in app.flashes('success')%}
<div class="success">{{ message }}</div>
{% endfor %}
{% for message in app.flashes('error')%}
<div class="error">{{ message }}</div>
{% endfor %}
<h1 class="center mat-2">Some Tricks</h1>
{% if app.user and app.user.isVerified %}
<div class="center">
    <a href="{{ path('app_add_trick')}}" class=" btn btn-dark">Add a Trick !</a>
</div>
{% endif %}
<div class="mal-1 mat-2 tricksContainer" id="bloctricks">
    <div class="container">
        <div class="row row-cols-5 align-items-start justify-content-center">
            {% set nbTricks = 0 %}
            {% for trick in tricks %}
            <div class="col mab-1">
                <div class="card" style="width: 16rem;" id="trick{{nbTricks}}">
                    
                      <img src="{{ trick.media }}"
                      class="card-img-top image_card" alt="..."> 

                    <div class="card-body">
                        <a href="trick/{{trick.slug}}">
                            <h5 class="card-title mar-1 ">{{ trick.name }}</h5>
                        </a>
                        {% if app.user and app.user.isVerified %}
                        <a href="/profil/edit/{{trick.id}}"><i class="fas fa-pencil-alt mar-1"></i></a>
                            <form method="post" action="{{ path('app_trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this amazing trick?');">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
                                <button class="fas"><i class="fas fa-trash-alt"></i></button>
                            </form>
                
                        {% endif %}
                    </div>
                </div>
            </div>
            {% set nbTricks = nbTricks + 1 %}
            {% endfor %}
        </div>
    </div>
</div>
{% if allTricksQty > nbTricks %}
<div class="center">
    <a href="/?showTricks={{nbTricks}}#trick{{nbTricks}}" class="btn btn-dark">Load more</a>
</div>
<a href="#up"><i class="fas fa-arrow-up"></i></a>
{% endif %}
<script src="{{asset('js/arrowGeoffray.js')}}"></script>
{% endblock %}

templates/main/trick.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.name }}!{% endblock %}

{% block body %}

<main>
    <div class="jumbotron" style="background-image: url('{{ asset('/uploads/' ~ trick.onTopPic) }}');">
       

    </div>
    
    {% for message in app.flashes('success')%}
    <div class="success">{{ message }}</div>
    {% endfor %}
    {% for message in app.flashes('error')%}
    <div class="error">{{ message }}</div>
    {% endfor %}
    <section>
        <div>  
            <hero 
                style="background-image:url({{ asset('/uploads/' ~ trick.onTopPic) }})">
                {% if app.user and app.user.isVerified %}
                <h1 class="center">{{ trick.name }}</h1>
                <a href="/profil/edit/{{trick.id}}"><i class="fas fa-pencil-alt mar-2"></i></a>

                <form method="post" action="{{ path('app_OnTopPic_delete', {'id': trick.id}) }}"
                    onsubmit="return confirm('Are you sure you want to delete this amazing picture?');">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
                    <button class="fas"><i class="fas fa-trash-alt mr-2"></i></button>
                </form>
               {% endif %}
            </hero>
        </div>
        <button class="mediaContainerButton" onclick="showHideMedias()">see medias</button>
        <div class="mediaContainer mat-2">
            {% for media in medias %}
            <a href="{{ asset('/uploads/' ~ media.filename)}}" class="thumbnail">
                {% if media.type == "image" %}
                <img src="{{ asset('/uploads/' ~ media.filename)}}" alt="Image 1" class="thumbnail" />
                {% else %}
                <video class="thumbnail">
                    <source src="{{ asset('/uploads/' ~ media.filename)}}" />
                </video>
                {% endif %}
            </a>
            {% endfor %}
            {% if trick.videoLink %}
            <iframe width="350" height="215" src="{{trick.videoLink}}" title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            {% endif %}
        </div>
        <p class="center mat-2">{{ trick.description }}</p>
        <div class="mediaContainer">
            <p>Catégorie : {{ category.name }}</p>
            <p>Crée le : {{ trick.createdAt|date('d.m.Y') }}</p>
            {% if trick.updateAt %}
            <p>modifié le : {{ trick.updateAt|date('d.m.Y')}}</p>
            {% endif %}
        </div>
        {% if app.user %}
        <hr>
        <div class="mab-2 center" id="addComment">
            {{form_start(form)}}
            {{form_widget(form.content)}}
            {{form_widget(form.submit)}}
            {{form_end(form)}}
        </div>
        {% endif %}
    </section>
    <hr>
    <section id="comments">
        <h2 class="center">Comments</h2>
        {% set nbComments = 0 %}
        {% for comment in comments %}
        {% if comment.parent == null %}
        <article id="comment{{nbComments}}">
            <img src="{{ asset('/uploads/' ~ comment.user.avatar)}}" alt="avatar" id="avatar" class="avatar">
            <span class="italic username">{{ comment.user.username }} said :</span>
            <span class="content">{{comment.content|raw}}</span>
            <span class="date">{{ comment.createdAt|date('d.m.Y')}}</span>
            <a href="#addComment" data-reply data-id="{{comment.id}}" class="btn btn-dark">Reply</a>

        </article>
        {% for reply in comment.reply %}
        <article class="replied">
            <img src="{{ asset('/uploads/' ~ reply.user.avatar)}}" alt="avatar" id="avatar" class="avatar">
            <span class="italic username">{{ reply.user.username }} replied : </span>
            <span class="content">{{reply.content|raw}}</span>
            <span class="date">{{ reply.createdAt|date('d.m.Y')}}</span>
        </article>
        {% endfor %}
        {% endif %}
        {% set nbComments = nbComments + 1 %}
        {% endfor %}
        {% if allCommentsQty > nbComments %}
        <div class="center">
            <a href="?showComments={{nbComments}}#comment{{nbComments}}" class="btn btn-dark">Load more</a>
        </div>
        {% endif %}
    </section>
</main>
{% block javascripts %}
<script>
    window.onload = () => {

        document.querySelectorAll("[data-reply]").forEach(element => {
            element.addEventListener("click", function () {
                document.querySelector("#comment_parentid").value = this.dataset.id;
            })
        })
    }
    function showHideMedias(){
        const mediaContainerButton = document.querySelector(".mediaContainerButton");
        const mediaContainer = document.querySelector(".mediaContainer");
        mediaContainer.classList.toggle("visible");
        mediaContainerButton.innerText = 
            mediaContainer.classList.contains("visible")
            ? "hide medias"
            : "see medias"; 
    }
</script>
{% endblock %}
{% endblock %}